### ISSUE TITLE
fastGzReader is not used

### ISSUE THREAD

**Issue by shenwei356** [brentp/xopen#2]
Hi, Brent,

I notice that your [last commit](https://github.com/brentp/xopen/commit/5ad1aa642714d4fe90b81c087633bf9657fdf4ac) had added the `fastGzReader`, but you did not use it. It's commented, see [https://github.com/brentp/xopen/blob/master/xopen.go#L140](https://github.com/brentp/xopen/blob/master/xopen.go#L140). Did you forget or intend to do so?

Wei

**Comment by brentp** [comment]
I was experimenting with it because it was quite a bit faster. But with the changes in go 1.7, the difference is small. I'll probably remove it soon.

**Comment by shenwei356** [comment]
It's really faster!

I did not notice the change in go 1.7.  I forked and will use `fastGzReader` until coming out another faster solution. 

thanks you Brent.

**Comment by brentp** [comment]
might be good to have a benchmark on, e.g. a VCF showing the difference. If it's still 2x, then it'd be good to turn it back on.

**Comment by brentp** [comment]
we could also default the Writer to `BestSpeed` level or to `HuffmanOnly` in go 1.7

**Comment by shenwei356** [comment]
I tested on big fasta/q files, the way using zcat is the fastest. I'll use this fork.
